Soup.OrderSystem.UI/Controllers/ProductController.cs
using AspNetCoreGeneratedDocument;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Soup.OrderSystem.Logic.DTO;
using Soup.OrderSystem.Logic.Interfaces;
using Soup.OrderSystem.Objects.Order;
using Soup.OrderSystem.UI.Models;
using System.Threading.Tasks;

namespace Soup.OrderSystem.UI.Controllers
{

    public class ProductController : Controller
    {
        private IProductServiceAsync _service;
        private IStockActionServiceAsync _actionService;
        
        public ProductController(IProductServiceAsync service, IStockActionServiceAsync actionService)
        {
            _service = service;
            _actionService = actionService;
        }
        //unused method
        //public IActionResult Products()
        //{
        //    return View();
        //}

        [Authorize(Roles = "Admin")]
        public IActionResult CreateProduct()
        {
            return View();
        }
        /// <summary>
        /// Finds the product that the user clicked on and passes along the details required.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            OrderProductModel orderProductModel = new();
            Product product = new();
            product = await _service.GetProduct(id);
            int currentStockAmount = await _actionService.GetCurrentStockAmount(product.ProductID);
            int availableStockAmount = await _actionService.GetAvailableStockAmount(product.ProductID);
            orderProductModel.ProductName = product.ProductName;
            orderProductModel.ProductID = id;
            orderProductModel.AmountInStock = currentStockAmount;
            orderProductModel.AvailableStock = availableStockAmount;
            return View(orderProductModel);
        }
        /// <summary>
        /// Gets a list of products and converts them to a list of ProductDTO's to return
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Overview()
        {
            List<ProductDTO> productDTOs = new List<ProductDTO>();
            List<Product> ProductList = await _service.GetProductsList();
            productDTOs = ProductList.Select(p => new ProductDTO
            {
                ProductID = p.ProductID,
                ProductName = p.ProductName
            }
            ).ToList();
            return View(productDTOs);
        }
        /// <summary>
        /// gets a list of products and converts them into a list of OrderProductModels to return
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetProducts()
        {
            List<OrderProductModel> productDTOs = new List<OrderProductModel>();
            List<Product> ProductList = await _service.GetProductsList();
            int currentStockAmount = 0;
            int availableStockAmount = 0;
            foreach (Product product in ProductList)
            {
                currentStockAmount = await _actionService.GetCurrentStockAmount(product.ProductID);
                availableStockAmount = await _actionService.GetAvailableStockAmount(product.ProductID);
                OrderProductModel orderProductModel = new OrderProductModel();
                orderProductModel.ProductID = product.ProductID;
                orderProductModel.ProductName = product.ProductName;
                orderProductModel.AmountInStock = currentStockAmount;
                orderProductModel.AvailableStock = availableStockAmount;
                productDTOs.Add(orderProductModel);
            }
            return View(productDTOs);
        }
        /// <summary>
        /// gets the Product the user clicked on and returns the required details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id)
        {
            ProductDTO productDTO = new();
            Product product = await _service.GetProduct(id);
            productDTO.ProductID = product.ProductID;
            productDTO.ProductName = product.ProductName;
            return View(productDTO);
        }
        /// <summary>
        /// gets the product the user clicked on and deletes it, then redirects it the GetProducts page
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int id)
        {
            await _service.DeleteProduct(id);
            return RedirectToAction("GetProducts");
        }
        /// <summary>
        /// Creates a new product, if the credentials are valid it redirects to the GetProducts page, if not valid, it returns to the form
        /// </summary>
        /// <param name="productDTO"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateProduct(ProductDTO productDTO)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateProduct(productDTO);
                return RedirectToAction("GetProducts");
            }
            else
            {
                return View(productDTO);
            }
        }
        /// <summary>
        /// updates a product, if the credentials are valid it redirects to the GetProducts page, if not valid, it returns to the form
        /// </summary>
        /// <param name="ProductDTO"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Update(ProductDTO ProductDTO)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateProduct(ProductDTO);
                return RedirectToAction("GetProducts");
            }
            else
            {
                return View(ProductDTO);
            }
        }

    }
}

Soup.OrderSystem.UI/Controllers/StockActionController.cs
using AspNetCoreGeneratedDocument;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Soup.OrderSystem.Logic;
using Soup.OrderSystem.Logic.DTO;
using Soup.OrderSystem.Logic.Interfaces;
using Soup.OrderSystem.Objects;
using Soup.OrderSystem.Objects.Customer;
using Soup.OrderSystem.Objects.Order;
using Soup.OrderSystem.UI.Models;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Soup.OrderSystem.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StockActionController : Controller
    {
        private IStockActionServiceAsync _stockActionService;
        private IOrderServiceAsync _orderService;
        private IProductServiceAsync _productService;
        public StockActionController(IStockActionServiceAsync stockActionService, IOrderServiceAsync orderService, IProductServiceAsync productService)
        {
            _stockActionService = stockActionService;
            _orderService = orderService;
            _productService = productService;
        }
        /// <summary>
        /// get a list of every stock action and converting it to a list of StockActionDTO's to return
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> GetStockActions()
        {
            List<StockActionDTO> stockActionDTOs = new List<StockActionDTO>();
            List<StockAction> stockActions = new List<StockAction>();
            stockActions = await _stockActionService.GetStockActionsList();
            stockActionDTOs = stockActions.Select(s => new StockActionDTO
            {
                Amount = s.Amount,
                Id = s.Id,
                ProductId = s.ProductId,
                OrderId = s.OrderId,
                StockActions = s.StockActionsEnum,
            }).ToList();
            return View(stockActionDTOs);
        }
        /// <summary>
        /// passes along a OrderProductModel with ProductId & ProductName to the view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> CreateStockAction(int id)
        {
            OrderProductModel model = new OrderProductModel();
            Product product = new();
            product = await _productService.GetProduct(id);
            model.ProductID = id;
            model.ProductName = product.ProductName;
            return View(model);
        }
        //accidental duplicate method apparently. Not going to fix it now because both are used in views.
        /// <summary>
        /// get a list of every stock action and converting it to a list of StockActionDTO's to return 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> ManageStock(int id)
        {   
            List<StockAction> stockActionsList = new List<StockAction>();
            List<StockActionDTO> stockActionDTOs = new List<StockActionDTO>();
            stockActionsList = await _stockActionService.GetStockActionsByProduct(id);
            stockActionDTOs = stockActionsList.Select(s => new StockActionDTO
            {
                Amount = s.Amount,
                Id = s.Id,
                ProductId = s.ProductId,
                OrderId = s.OrderId,
                StockActions = s.StockActionsEnum,
            }).ToList();
            return View(stockActionDTOs);
        }
        /// <summary>
        /// Creates a stock action, if an order hasn't been created yet, create one using the customer id "k1" which is designated to be the admin's customerId. Then redirects to main page.
        /// </summary>
        /// <param name="orderProductModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> CreateStockAction(OrderProductModel orderProductModel)
        {
            int ? orderId = HttpContext.Session.GetInt32("OrderId");
            if (orderId == null)
            {
                //
                HttpContext.Session.SetInt32("OrderId", await _orderService.CreateOrder("k1"));
                orderId = HttpContext.Session.GetInt32("OrderId");
            }
            int notNullId = orderId.Value;
            StockActionDTO stockActionDTO = new();
            stockActionDTO.Amount = orderProductModel.ProductAmount;
            stockActionDTO.ProductId = orderProductModel.ProductID;
            stockActionDTO.OrderId = notNullId;
            stockActionDTO.StockActions = orderProductModel.StockAction;
            await _stockActionService.CreateStockAction(stockActionDTO);
            return RedirectToAction("Overview", "product");
        }
    }
}

Soup.OrderSystem.UI/Views/Product/CreateProduct.cshtml
@{
    ViewData["Title"] = "Create";
}
@model Soup.OrderSystem.Logic.DTO.ProductDTO
<form method="Post" asp-controller="Product" asp-action="CreateProduct">
    <div class="form-group">
        <h1>Create Product</h1>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ProductName" class="control-label mt-4">Name:</label>
            <input type="text" class="form-control" asp-for="ProductName" />
            <span asp-validation-for="ProductName" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-4">Ok</button>
    </div>
</form>

Soup.OrderSystem.UI/Views/Product/Details.cshtml
@model OrderProductModel

<h1>
    Product details
</h1>
<form method="post" asp-action="UpdateAmount" asp-controller="ShoppingCart">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <bold> <h4 class="card-title">@Model.ProductName</h4></bold>
                <input hidden asp-for="@Model.ProductID" />
                <h5 class="card-subtitle">Out of @Model.AmountInStock products, only @Model.AvailableStock are still available for order</h5>
                @if(User.IsInRole("Admin"))
                {
                    <a class="btn btn-outline-dark mt-3" asp-action="ManageStock" asp-controller="StockAction" asp-route-id="@Model.ProductID">Manage stock</a>
                }
                <p class="card-text text-lg-center mt-3">A delicious can of soup!</p>
                <div class="form-group">
                    <label asp-for="ProductAmount" class="control-label mt-4">Amount:</label>
                    <input type="number" min="1" asp-for="ProductAmount"/>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Add to cart</button>
            <p class="alert-danger">@ViewData["Error"]</p>
        </div>
    </div>
</form>

Soup.OrderSystem.UI/Views/Product/GetProducts.cshtml
@using Soup.OrderSystem.Logic.DTO
@model List<OrderProductModel>
@{
    ViewData["Title"] = "View";
}

<h1>These are all the products that have been registered in the system</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th># in stock</th>
            <th># available in stock</th>
            <th>Edit stock</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (OrderProductModel item in Model)
        {
            <tr>
                <td>@item.ProductName</td>
                <td>@item.AmountInStock</td>
                <td>@item.AvailableStock</td>
                <td>
                    <a class="btn btn-link" asp-controller="StockAction" asp-action="CreateStockAction" asp-route-id="@item.ProductID">Edit stock</a>
                </td>
                <td>
                    <a class="btn btn-info" asp-controller="Product" asp-action="Update" asp-route-id="@item.ProductID">Update information</a>
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="Product" asp-action="Delete" asp-route-id="@item.ProductID">Remove</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Soup.OrderSystem.UI/Views/Product/Overview.cshtml
@using Soup.OrderSystem.Logic.DTO
@model List<ProductDTO>
@{
    ViewData["HomePage"] = "Overview";
}
<div class="container text-center">
    <div class="row">
@foreach (ProductDTO product in Model)
{       <input type="hidden" value="@product.ProductID" />
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">@product.ProductName</h4>
                    <a asp-action="Add" asp-controller="ShoppingCart" asp-route-id="@product.ProductID" class="btn btn-primary">Add to Cart</a>
                    <a asp-action="Details" asp-controller="Product" asp-route-id="@product.ProductID" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>

    
}
</div>
</div>

Soup.OrderSystem.UI/Views/Product/Products.cshtml
@{
    ViewData["Title"] = "Home-Products";
}

<div class="text-center">
    <h1 class="display-4">Products</h1>
    <a asp-action="GetProducts" class="btn btn-primary">Overview</a>
    <a asp-action="CreateProduct" class="btn btn-info">Add Product</a>
</div>

Soup.OrderSystem.UI/Views/Product/Update.cshtml
@model Soup.OrderSystem.Logic.DTO.ProductDTO
@{
    ViewData["Title"] = "Update";
}
<h1>Update Product Name</h1>
<hr />
<div class="row">
    <form asp-action="Update" method="post">
        <div class="form-group">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.ProductID"/>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Save" class="btn btn-primary mt-4">Ok</button>
            </div>
            <div>
                <a class="link-secondary mt-4" asp-action="GetProducts">Go Back</a>
            </div>
        </div>
    </form>
</div>